<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; }
        h1 { color: #0b5394; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; font-size: 12px; }
        th { background-color: #f4f4f4; }
        .footer { margin-top: 40px; font-size: 12px; text-align: center; color: #888; }
    </style>
</head>
<body>
    <h1>Payment Receipt</h1>
    <p><strong>Invoice ID:</strong> {{ $invoiceId }}</p>
    <p><strong>Customer:</strong> {{ $customerName }}</p>
    <p><strong>Date:</strong> {{ $paymentDate }}</p>
    <p><strong>Method:</strong> {{ $paymentMethod }}</p>
    <p><strong>Amount Paid:</strong> Rp {{ number_format($amountPaid, 0, ',', '.') }}</p>

    <table>
        <tr>
            <th>No</th>
            <th>Item</th>
            <th>Qty</th>
            <th>Unit Price</th>
            <th>Subtotal</th>
        </tr>
        @foreach($items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item['product'] }}</td>
                <td>{{ $item['delivered_qty'] }}</td>
                <td>Rp {{ number_format($item['unit_price'], 0, ',', '.') }}</td>
                <td>Rp {{ number_format($item['subtotal'], 0, ',', '.') }}</td>
            </tr>
        @endforeach
    </table>

    <h3>Total: Rp {{ number_format($tableTotal, 0, ',', '.') }}</h3>

    <div class="footer">
        This is an official receipt generated by PT. Nama Perusahaan. Please keep this document for your records.
    </div>
</body>
</html>
