<?php

namespace App\Filament\Resources;

use App\Filament\Resources\DemandForecastResource\Pages;
use App\Models\DemandForecast;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use BezhanSalleh\FilamentShield\Contracts\HasShieldPermissions;
use BezhanSalleh\FilamentShield\Traits\HasShieldFormComponents;

class DemandForecastResource extends Resource
{
    use HasShieldFormComponents;
    protected static ?string $model = DemandForecast::class;

    protected static ?string $navigationIcon = 'heroicon-o-arrow-trending-up';
    protected static ?string $navigationGroup = 'Inventory';
    protected static ?int $navigationSort = 2; // Set the order in the navigation

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                // Form is not needed because this data is for display only (read-only)
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('sub_part_number')
                    ->label('Part Code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('sub_part_name')
                    ->label('Part Name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('average_monthly_sales')
                    ->label('Avg. Monthly Sales')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('current_stock')
                    ->label('Current Stock')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('recommended_stock_level')
                    ->label('Recommended Stock')
                    ->numeric()
                    ->sortable()
                    ->color('primary')
                    ->weight('bold'),
                Tables\Columns\TextColumn::make('forecast_date')
                    ->label('Forecast Date')
                    ->date()
                    ->sortable(),
            ])
            ->defaultSort('average_monthly_sales', 'desc');
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDemandForecasts::route('/'),
        ];
    }
    
    // Disable the Create button because the data is generated by the system
    public static function canCreate(): bool
    {
        return false;
    }
}
